# Default values for Epay_Merchant_FE.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

replicaCount: 1

image:
  #repository: registry.dev.sbiepay.sbi:8443/ubi9/{{ .Chart.Name }}
  repository: registry.dev.sbiepay.sbi:8443/ubi9/{{ .Chart.Name }}
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  ##tag: "v-develop-20251103101240"
  tag: "3110251"
  
  

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

configMap: {}


securityContext: {}


service:
  type: ClusterIP
  port: 8080

ingress: {}


namespace: dev-frontend
gatewayName: dev-istio-system/dev-gateway
virtualServiceName: epay_merchantintegration_fe
serviceName: epay_merchantintegration_fe
prefixName:  /merchantintegration 
servicePort: 8080
gatewayPort: 80
gatewayHost: "dev.epay.sbi"

readinessProbe: {}
livenessProbe: {}


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
________valur.yaml______________


    - namespace: frontend
      description: "Frontend services"
      services:
        - name: epay_merchant_fe
          release: merchantfe
          chart: epay_merchant_fe
          health_check: /health
          environments:
            - dev
            - sit
            - uat
            - int
            - pre-prod
            - perf
            - pre-prod-dc
            - prod-dr
            - prod-dc
        
        - name: epay_transaction_fe
          release: transactionfe
          chart: epay_transaction_fe
          health_check: /health
          environments:
            - dev
            - sit
            - uat
            - int
            - pre-prod
            - perf
            - pre-prod-dc
            - prod-dr
            - prod-dc

        - name: epay_maintenance_fe
          release: maintenancefe
          chart: epay_maintenance_fe
          health_check: /health
          environments:
            - dev
            - sit
            - uat
            - int
            - pre-prod
            - perf
            - pre-prod-dc
            - prod-dr
            - prod-dc

        - name: epay_website
          release: websitefe
          chart: epay_website
          health_check: /health
          environments:
            - dev
            - sit
            - uat
            - int
            - pre-prod
            - perf
            - pre-prod-dc
            - prod-dr
            - prod-dc

        - name: epay_merchantintegration_fe
          release: merchant-int
          chart: epay-merchant-int
          health_check: /health
          environments:
            - dev
            - sit
            - uat
            - int
            - pre-prod
            - perf
            - pre-prod-dc
            - prod-dr
            - prod-dc
_______service.yaml___________

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "Epay_Merchantintegration_FE.fullname" . }}
  labels:
    {{- include "Epay_Merchantintegration_FE.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "Epay_Merchantintegration_FE.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "Epay_Merchantintegration_FE.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "Epay_Merchantintegration_FE.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ tpl .Values.image.repository $ }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
____________deployment.yaml________________
