# Default values for Epay_Merchant_FE.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

replicaCount: 1

image:
  #repository: registry.dev.sbiepay.sbi:8443/ubi9/{{ .Chart.Name }}
  repository: registry.dev.sbiepay.sbi:8443/ubi9/{{ .Chart.Name }}
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  ##tag: "v-develop-20251103101240"
  tag: "3110251"
  
  

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

configMap: {}


securityContext: {}


service:
  type: ClusterIP
  port: 8080

ingress: {}


namespace: dev-frontend
gatewayName: dev-istio-system/dev-gateway
virtualServiceName: epay_merchantintegration_fe
serviceName: epay_merchantintegration_fe
prefixName:  /merchantintegration 
servicePort: 8080
gatewayPort: 80
gatewayHost: "dev.epay.sbi"

readinessProbe: {}
livenessProbe: {}


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
________valur.yaml______________


    - namespace: frontend
      description: "Frontend services"
      services:
        - name: epay_merchant_fe
          release: merchantfe
          chart: epay_merchant_fe
          health_check: /health
          environments:
            - dev
            - sit
            - uat
            - int
            - pre-prod
            - perf
            - pre-prod-dc
            - prod-dr
            - prod-dc
        
        - name: epay_transaction_fe
          release: transactionfe
          chart: epay_transaction_fe
          health_check: /health
          environments:
            - dev
            - sit
            - uat
            - int
            - pre-prod
            - perf
            - pre-prod-dc
            - prod-dr
            - prod-dc

        - name: epay_maintenance_fe
          release: maintenancefe
          chart: epay_maintenance_fe
          health_check: /health
          environments:
            - dev
            - sit
            - uat
            - int
            - pre-prod
            - perf
            - pre-prod-dc
            - prod-dr
            - prod-dc

        - name: epay_website
          release: websitefe
          chart: epay_website
          health_check: /health
          environments:
            - dev
            - sit
            - uat
            - int
            - pre-prod
            - perf
            - pre-prod-dc
            - prod-dr
            - prod-dc

        - name: epay_merchantintegration_fe
          release: merchant-int
          chart: epay-merchant-int
          health_check: /health
          environments:
            - dev
            - sit
            - uat
            - int
            - pre-prod
            - perf
            - pre-prod-dc
            - prod-dr
            - prod-dc
_______service.yaml___________

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "Epay_Merchantintegration_FE.fullname" . }}
  labels:
    {{- include "Epay_Merchantintegration_FE.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "Epay_Merchantintegration_FE.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "Epay_Merchantintegration_FE.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "Epay_Merchantintegration_FE.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ tpl .Values.image.repository $ }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
____________deployment.yaml________________

Running with gitlab-runner 17.8.0 (e4f782b3)
  on DR-Gitlab-runner t1_CpKnL, system ID: s_5f020bf813e7
Resolving secrets
Preparing the "docker" executor
00:04
Using Docker executor with image registry.dev.sbiepay.sbi:8443/library/rhelgit:latest ...
Using helper image:  registry.dev.sbiepay.sbi:8443/library/gitlab-runner-helper:latest  (overridden, default would be  registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.8.0 )
Pulling docker image registry.dev.sbiepay.sbi:8443/library/gitlab-runner-helper:latest ...
Using docker image sha256:c95744588b6d7e170a6866854932de40eaf1b5ed229ed818cba6a87a1f885773 for registry.dev.sbiepay.sbi:8443/library/gitlab-runner-helper:latest with digest registry.dev.sbiepay.sbi:8443/library/gitlab-runner-helper@sha256:ebbf1c21e4272ae1f8c18b034d390809c836c2fc68c0f0f6d3a5aff9760aabf5 ...
Using helper image:  registry.dev.sbiepay.sbi:8443/library/gitlab-runner-helper:latest  (overridden, default would be  registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.8.0 )
Using docker image sha256:c95744588b6d7e170a6866854932de40eaf1b5ed229ed818cba6a87a1f885773 for registry.dev.sbiepay.sbi:8443/library/gitlab-runner-helper:latest with digest registry.dev.sbiepay.sbi:8443/library/gitlab-runner-helper@sha256:ebbf1c21e4272ae1f8c18b034d390809c836c2fc68c0f0f6d3a5aff9760aabf5 ...
Pulling docker image registry.dev.sbiepay.sbi:8443/library/rhelgit:latest ...
Using docker image sha256:cc9b278413b4f7940e4ec53a72ef8389e1f78fe99aeb20c8af62f14e706074d4 for registry.dev.sbiepay.sbi:8443/library/rhelgit:latest with digest registry.dev.sbiepay.sbi:8443/library/rhelgit@sha256:8576ae23d4f1ae2cc0e30d6c1b401fee3a2386faab50c58e97b726c3dc028d09 ...
Preparing environment
00:01
Using helper image:  registry.dev.sbiepay.sbi:8443/library/gitlab-runner-helper:latest  (overridden, default would be  registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.8.0 )
Using docker image sha256:c95744588b6d7e170a6866854932de40eaf1b5ed229ed818cba6a87a1f885773 for registry.dev.sbiepay.sbi:8443/library/gitlab-runner-helper:latest with digest registry.dev.sbiepay.sbi:8443/library/gitlab-runner-helper@sha256:ebbf1c21e4272ae1f8c18b034d390809c836c2fc68c0f0f6d3a5aff9760aabf5 ...
Running on runner-t1cpknl-project-23-concurrent-0 via Gitlab-DR-Runr...
Getting source from Git repository
00:09
$ git config --global http.proxy $HTTP_PROXY; git config --global https.proxy $HTTPS_PROXY; git config --global no.proxy $NO_PROXY
Fetching changes...
Initialized empty Git repository in /tmp/builds/epay/devops/deployment/.git/
Created fresh repository.
Checking out dc5c5027 as detached HEAD (ref is main)...
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:01
Using docker image sha256:cc9b278413b4f7940e4ec53a72ef8389e1f78fe99aeb20c8af62f14e706074d4 for registry.dev.sbiepay.sbi:8443/library/rhelgit:latest with digest registry.dev.sbiepay.sbi:8443/library/rhelgit@sha256:8576ae23d4f1ae2cc0e30d6c1b401fee3a2386faab50c58e97b726c3dc028d09 ...
$ set -eo pipefail # collapsed multi-line command
Repository root: /tmp/builds/epay/devops/deployment
Debug: GitLab CI Variables:
CI_COMMIT_SHA: dc5c50272c89b7f795c08c77e767c8fa1a854b5a
CI_COMMIT_BEFORE_SHA: 58d1530014b561742004ec4aea6ce94b002d5382
CI_COMMIT_REF_NAME: main
CI_COMMIT_CHANGED_FILES: 
Debug: CI_COMMIT_CHANGED_FILES is empty, trying to get changed files manually...
Debug: Manually detected changed files:
dev/charts/epay_merchantintegration/templates/deployment.yaml
dev/charts/epay_merchantintegration/templates/hpa.yaml
dev/charts/epay_merchantintegration/templates/service.yaml
dev/charts/epay_merchantintegration/templates/serviceaccount.yaml
dev/charts/epay_merchantintegration/templates/tests/test-connection.yaml
Changed files: dev/charts/epay_merchantintegration/templates/deployment.yaml
dev/charts/epay_merchantintegration/templates/hpa.yaml
dev/charts/epay_merchantintegration/templates/service.yaml
dev/charts/epay_merchantintegration/templates/serviceaccount.yaml
dev/charts/epay_merchantintegration/templates/tests/test-connection.yaml
Found changed chart path: dev/charts/epay_merchantintegration
Detected environment from changed path: dev
Detected service from changed path: epay_merchantintegration
Using service: epay_merchantintegration
Using environment: dev
Found chart at path: /tmp/builds/epay/devops/deployment/dev/charts/epay_merchantintegration
$ set -eo pipefail # collapsed multi-line command
$ set -eo pipefail # collapsed multi-line command
Error: Missing NAMESPACE configuration for service 'epay_merchantintegration'
Running after_script
00:01
Running after script...
$ rm -f /tmp/services_config.yml
Uploading artifacts for failed job
00:01
Uploading artifacts...
WARNING: build.env: no matching files              
ERROR: No files to upload                          
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1

a error asuchi kan mu karibi a fix haba 
